package com.citi.ArbApplication.Enum;


public enum FxEnum {
	
	SPOT_BID_RANGE(0.5),
	SPOT_BID_MIN(105.0),
	FORWARD_BID_RANGE(0.5),
	FORWARD_BID_MIN(4.9),
	INTEREST_RATE_USD_BID_RANGE(0.5),
	INTEREST_RATE_USD_BID_MIN(4.9),
	INTEREST_RATE_JPY_BID_RANGE(0.1),
	INTEREST_RATE_JPY_BID_MIN(0.3),
	TRANSACTION_COST,
	FWD_ARB_QUANTITY(1000);
	
	FxEnum(double d) {
		
	}
	FxEnum() {
		
	}
	

}
